name: Build

on: [push]

jobs:
  build:

    name: Plataform Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - name: node_module Instalation
      run: npm install
    - name: Ionic cli instalation
      run: npm install -g @ionic/cli
    - name: Capacitor instalation
      run: npm install -g @capacitor/cli @capacitor/core
    - name: Build
      run: ionic build
    - name: Capacitor Update
      run: npx capacitor sync
    - name: Open Capacitor android
      run: npx capacitor open android
    
